### ISSUE TITLE
Support MMPU Add On

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-roles#6]
We should look at supporting MMPU Add On. If active, we should be able to set user's to have multiple roles at the same time.

**Comment by andreasputlitz** [comment]
Hi, I am absolutely new to GitHub and don't know how the netiquette for this is. But, I wanted to seize the opportunity and ask if the multiple roles at the same time and/or the MMPU integration are something that are being actively pursued? I can definitely say we would be very exited to see this implemented.

**Comment by kimcoleman** [comment]
This is an approved improvement to the code. 

We should instead of overwriting the default role on the site, add the additional level-specific role. This would make the plugin MMPU compatible but also ensure that default site functionality for the main site + plugins like bbPress and BuddyPress are not affected by the roles plugin.

We can consider extending to include functionality of the Members plugin or User Role Editor / Role Scoper.

**Comment by andrewlimaza** [comment]
This has been added to the latest version and should be released soon. Feel free to test the 'dev' branch - @andreasputlitz. I am going to close this issue.

What happens is if MMPU is installed it will add and remove roles based on the levels being added/removed. User's may keep the default WordPress role as well.
